apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    app.kubernetes.io/part-of: lego-pincer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: lego-pincer-secrets
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    app.kubernetes.io/part-of: lego-pincer-app
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lego-pincer
  labels:
    app: lego-pincer
    app.kubernetes.io/part-of: lego-pincer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lego-pincer
  template:
    metadata:
      labels:
        app: lego-pincer
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            [
              "sh",
              "-c",
              "until nc -z postgres 5432; do echo \"waiting for postgres...\";
                sleep 2; done;",
            ]
      containers:
        - name: lego-pincer
          image: kisbogdan/lego-pincer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: lego-pincer-secrets
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: lego-pincer
  labels:
    app: lego-pincer
    app.kubernetes.io/part-of: lego-pincer-app
spec:
  selector:
    app: lego-pincer
  ports:
    - port: 8080
      targetPort: 8080
